### PR TITLE
Powerful Find command && Fix Bug in List

### LINKED ISSUE #17: Find Tasks within Time Period

### LINKED ISSUE #18: Find Tasks for Today

### LINKED ISSUE #19: Find Upcoming Tasks for the Week

### LINKED ISSUE #24: Find Upcoming Tasks with Specific Description

### LINKED ISSUE #97: List Command Wrongly Parsed
`list jiwjfoffjoji` should not be same as `list`. We should give an error message indicating that `list jiwjfoffjoji` is  a wrong command.

### LINKED ISSUE #117: Code quality feedback for A0148037E
- public class SwitchTaskCategoryEvent extends BaseEvent {
This class name looks self-explanatory but I am still not sure why it exists. In cases where there are such non-intuitive reasons for a class add a header comment and explain what purpose it serves.

 //TODO to remove
    private static String getFxmlFromType(String type) {
..............
- remove defunct code and comments to such code. also do not leave them commented out. Simply remove it; commit it with a meaningful message.  you can always revert to the commit point to get the code block back.

- Much of your codebase is UI which is fine. Try to do some code in some other functional part as well.

- Method void fillInnerParts() { 
can be more readable. Looks cluttered. Add blank lines to separate different logical parts of a method

- There is hardly any test code. Write some test code for a solid part of your codebase to prove that you have covered that as well.  The only test code I see is a stub like stuff for Tasks. Do yo intend to create a a stub for Task Class and is it just test data for the tests to run.. The two are different.

### PR DESCRIPTION
**Pull request by VeryLazyBoy**
Fixes #17 
Fixes #18 
Fixes #19 
Fixes #24 
Fixes #97 
Fixes #117

### CODE REVIEW

**Comment by VeryLazyBoy** [comment]
@howsiwei , please help me check my implementation and give me some feedback.  Thanks!

File: src/main/java/seedu/geekeep/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -11,20 +19,84 @@
...
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all tasks whose titles contain any of "
-            + "the specified keywords (case-sensitive) and displays them as a list with index numbers.\n"
-            + "Parameters: KEYWORD [MORE_KEYWORDS]...\n"
-            + "Example: " + COMMAND_WORD + " alice bob charlie";
+            + "the specified keywords (case-sensitive)\n"
+            + "or whose date is between specified time duration "
+            + "or whose tag list contains any of the specified tags.\n "
+            + "Parameters: [KEYWORD]... [a/EARLIEST_TIME] [b/LATEST_TIME] [t/TAG]...\n"
+            + "Example: " + COMMAND_WORD + " CS3230 Midterm a/04-04-17 0000 t/exam";
+    public static final String MESSAGE_TIME_CONSTRAINTS = "The time a task happens before should be later "
```
Comment (yirui94) [inline src/main/java/seedu/geekeep/logic/commands/FindCommand.java:27]: Should use the message time constraint defined in task creation to be consistent. Phrasing is also confusing

File: src/main/java/seedu/geekeep/logic/commands/FindCommand.java [hunk 2]
```diff
@@ -11,20 +19,84 @@
...
+
+    private void addFilterMessage(Set<String> keywords, Optional<String> earliestTime,
+            Optional<String> latestTime,
+            Set<String> tags) {
+        if (!keywords.isEmpty()) {
+            datailedSuccessMsg  += "Contains any of keywords in " + keywords + " in title;\n";
+        }
+
+        if (earliestTime.isPresent()) {
+            datailedSuccessMsg += "Has starting time[event] or deadline[deadline] after "
```
Comment (yirui94) [inline src/main/java/seedu/geekeep/logic/commands/FindCommand.java:78]: 'datailed' is mispelled.

Phrasing is inconsistent. 

> Has starting time (events) or ending time (deadlines) after ...

**Review by yirui94 — APPROVED** [review]
